### ISSUE TITLE
Join 1.

### ISSUE THREAD

**Issue by robyle** [Deali-Axy/CrawlCenterNet#2]
![image](https://user-images.githubusercontent.com/11662528/183329018-fdc4b592-d153-4816-b4d5-42934d462005.png)

视乎项目跑起来样式有很大问题哦。

**Comment by Deali-Axy** [comment]
本项目的静态资源使用libman管理，运行项目之前需要先拉取libman静态资源（在VS中可以操作）~

**Comment by wbx58585888** [comment]
libman需要拉取哪些静态资源？

**Comment by wbx58585888** [comment]
> 本项目的静态资源使用libman管理，运行项目之前需要先拉取libman静态资源（在VS中可以操作）~

请问libman需要拉取哪些静态资源？

**Comment by Deali-Axy** [comment]
@wbx58585888 

具体静态资源列表在: [CrawlCenter.Web](https://github.com/Deali-Axy/CrawlCenterNet/tree/master/CrawlCenter.Web)/libman.json

使用VS打开项目可以选择自动获取。

或者使用 libman 的命令行

```bash
dotnet tool install -g Microsoft.Web.LibraryManager.Cli
cd CrawlCenter.Web
libman restore
```

**Comment by wbx58585888** [comment]
> @wbx58585888
> 
> 具体静态资源列表在: [CrawlCenter.Web](https://github.com/Deali-Axy/CrawlCenterNet/tree/master/CrawlCenter.Web)/libman.json
> 
> 使用VS打开项目可以选择自动获取。
> 
> 或者使用 libman 的命令行
> 
> ```shell
> dotnet tool install -g Microsoft.Web.LibraryManager.Cli
> cd CrawlCenter.Web
> libman restore
> ```
点击数据采集和项目管理，都报错，报错如下，请帮忙看一下
![image](https://user-images.githubusercontent.com/55383628/231947583-01e2996f-92b0-4cd0-bc22-d3178a1d63fd.png)

![image](https://user-images.githubusercontent.com/55383628/231947477-3f90de26-83ea-4fea-a456-7cfe1713e66d.png)

**Comment by Deali-Axy** [comment]
检查一下数据库里是不是没有这个表，需要的话开启 FreeSQL 的 AutoSyncStructure 功能进行表结构同步

**Comment by wbx58585888** [comment]
> 
app.db是这样的
![image](https://user-images.githubusercontent.com/55383628/231985547-93f01254-a23e-4d6d-8567-f4d7c31412a0.png)
appsetting里的HangfireMySql没有找到使用的地方
![image](https://user-images.githubusercontent.com/55383628/231985798-84405b62-12f7-4246-bb41-0f1796331440.png)
FreeSQL 的 AutoSyncStructure 是开启的，运行后还是会报上面的错误
![image](https://user-images.githubusercontent.com/55383628/231986099-9ba11c3f-2c95-4375-bd53-276a9182c129.png)

**Comment by Deali-Axy** [comment]
可以尝试手动创建这个表

```sql
create table ProjectProjectTag
(
    ProjectId    CHARACTER(36),
    ProjectTagId CHARACTER(36)
);
```

**Comment by wbx58585888** [comment]
> 可以尝试手动创建这个表
> 
> ```sql
> create table ProjectProjectTag
> (
>     ProjectId    CHARACTER(36),
>     ProjectTagId CHARACTER(36)
> );
> ```

有新的表缺失报错，可否提供一下完整的数据表
![image](https://user-images.githubusercontent.com/55383628/232005369-8c21bc70-bb7c-4e6b-87f1-08de794ef728.png)

**Comment by Deali-Axy** [comment]
编辑 `CrawlCenter.Data/Extensions/ConfigureFreeSql.cs`  代码

```c#
var freeSql = new FreeSqlBuilder()
    .UseConnectionString(DataType.Sqlite, configuration.GetConnectionString("SQLite"))
    .UseAutoSyncStructure(true)
    .Build();
```

开启 `UseAutoSyncStructure` 自动表结构同步，即可自动生成数据表。

**Comment by Deali-Axy** [comment]
数据库初始化SQL脚本：

```sql
create table CrawlTask
(
    Id          CHARACTER(36)
        primary key,
    Name        NVARCHAR(255),
    DisplayName NVARCHAR(255),
    Description NVARCHAR(255),
    ProjectId   CHARACTER(36),
    CodeDir     NVARCHAR(255),
    Cmd         NVARCHAR(255),
    UserId      CHARACTER(36)
);

create table Project
(
    Id          CHARACTER(36)
        primary key,
    Name        NVARCHAR(255),
    Description NVARCHAR(255)
);

create table ProjectProjectTag
(
    ProjectId    CHARACTER(36),
    ProjectTagId CHARACTER(36)
);

create table ProjectTag
(
    Id   CHARACTER(36)
        primary key,
    Name NVARCHAR(255)
);

create table RecurringTask
(
    Id          CHARACTER(36)
        primary key,
    Name        NVARCHAR(255),
    CrawlTaskId CHARACTER(36),
    Cron        NVARCHAR(255),
    Parameters  NVARCHAR(255),
    Description NVARCHAR(255),
    IsEnable    BOOLEAN not null
);

create table User
(
    Id             CHARACTER(36)
        primary key,
    Name           NVARCHAR(255),
    Password       NVARCHAR(255),
    Phone          NVARCHAR(255),
    DateTimeJoined DATETIME
);

```
